Controllers/AccountController.cs
//using ALR_02.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Remoting.Messaging;
using System.Web;
using System.Web.Mvc;
using AirLine_ClassLibrary;


namespace ALR_02.Controllers
{
    public class AccountController : Controller
    {
        // GET: Account

        //  private VirtusaDBEntities2 db = new VirtusaDBEntities2();





        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult FlightsList(string SearchBy, string searchValue)
        {
            /*            try
                        {
                            var collegeList = db.Colleges.ToList();
                            if (collegeList.Count == 0)
                            {
                                TempData["InfoMessage"] = " Flights are not available in the Database.";
                            }
                            else
                            {
                                if (string.IsNullOrEmpty(searchValue))
                                {
                                    TempData["InfoMessage"] = "Please Provide Search Value";
                                    return View(collegeList);

                                }
                                else if (SearchBy == "CollegeName")
                                {

                                    var searchByCollege = collegeList.Where(p => p.CollegeName.ToLower().Contains(searchValue.ToLower()));
                                    return View(searchByCollege);

                                }
                                else if ((SearchBy == "UniversityName"))
                                {
                                    var searchByUniversity = collegeList.Where(p => p.UniversityName.ToLower().Contains(searchValue.ToLower()));
                                    return View(searchByUniversity);
                                }
                            }
                            return View(collegeList);
                        }
                        catch (Exception ex)
                        {
                            TempData["ErrorMessage"] = ex.Message;
                            return View();
                        }
            */
            return View();
        }

    









        public ActionResult Profile()
        {
            return View();
        }


        public ActionResult Login()
        {
            LoginModel objLoginModel = new LoginModel();
            return View(objLoginModel);
        }
        public ActionResult Register()
        {
            RegisterModel objUserModel = new RegisterModel();
            return View(objUserModel);
        }


        [HttpPost]
        public ActionResult Register(RegisterModel objUserModel)
        {
            if (ModelState.IsValid)
            {
                RegisterModel objUSer = new RegisterModel();
               // objUSer.CreatedOn = DateTime.Now;
                // obj.UserId = objUserModel.UserId;
                objUSer.Username = objUserModel.Username;
               // objUSer.LastName = objUserModel.LastName;
                objUSer.EmailId = objUserModel.EmailId;
                objUSer.Password = objUserModel.Password;
               // objUserDBEntities.Users.Add(objUSer);
                //objUserDBEntities.SaveChanges();
               // objUserModel = new UserModel();
                //objUserModel.SuccessMessage = "User Registered successfully";
                // Console.log();
                //  UserModel objUserModel = new UserModel();
                return View(objUserModel);
            }
            else
            {
                return View();
            }
        }




        [HttpPost]
        public ActionResult Login(LoginModel objLoginModel)
        {
            /* if (ModelState.IsValid)
             {
                // var obj = objUserDBEntities.Users.Where(s => s.Email.Equals(objLoginModel.Email) && s.Password.Equals(objLoginModel.Password)).FirstOrDefault();
               //  if (obj != null)
                 {
                    // Session["Email"] = objLoginModel.Email;
                     return RedirectToAction("Index", "Home");
                     //return Redirect("/Home/Index");
                 }
                 else
                 {
                     ModelState.AddModelError("Error", "Email and Password is not Matching");
                     ViewBag.LoginError = "Invalid";
                     return View();
                 }
             }
             else
             {
                 ModelState.AddModelError("Error", "Email and Password is not Matching");
                 ViewBag.LoginError = "Please Enter EmailID and Pasword";
                 return View();
             }
             // objLoginModel=new LoginModel();*/

            //return Redirect("/Home/Index");
            return View(objLoginModel);
        }
    }
}

Controllers/FlightsController.cs
using AirLine_ClassLibrary;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ALR_02.Controllers
{
    public class FlightsController : Controller
    {
        // GET: Flights
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Booking()
        {
            return View();
        }
        public ActionResult Payments()
        {
            return View();
        }
        public ActionResult Booking_Form()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Flights_Details(Flights objLoginModel)
        {

            if (ModelState.IsValid)
            {
                return View();
            }
            return View(objLoginModel);
        }

        public ActionResult Flights_Details()
        {
            Flights objFlights = new Flights();
            if (ModelState.IsValid)
            {
                return View();
            }
            return View(objFlights); 
        }




    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ALR_02.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/InfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ALR_02.Controllers
{
    public class InfoController : Controller
    {
        // GET: Info
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult FAQs()
        {
            return View();
        }
        public ActionResult Reviews()
        {
            return View();
        }
        public ActionResult PrivacyPolicy()
        {
            return View();
        }
        public ActionResult Terms_Conditions()
        {
            return View();
        }

    }
}

Views/Flights/Flights_Details.cshtml
@model AirLine_ClassLibrary.Flights

@{
    ViewBag.Title = "Flights_Details";
}

<!DOCTYPE html>
<html lang="en">
<head>

    <title>Flight Details</title>
</head>
<style>
    html, body {
        max-width: 100%;
        overflow-x: hidden;
    }

    * {
        margin: 0;
        padding: 0;
    }

    body {
        background-color: #fdf2e9;
        background-size: cover;
    }

    .Heading {
        // text-align: center;
        padding-left: 550px;
        padding-top: 25px;
        padding-bottom: 25px;
        // text-decoration-line: underline;
    }

    .flightsContainer {
        text-align: left;
        //margin: 20px 250px 20px 250px;
    }

    .col {
        padding: 12px;
    }

    .styled {
        border: 0;
        line-height: 2.5;
        padding: 0 20px;
        font-size: 1rem;
        text-align: center;
        color: #fff;
        text-shadow: 1px 1px 1px #000;
        border-radius: 10px;
        background-color: rgb(31, 241, 108);
        background-image: linear-gradient(to top left, rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.2) 30%, rgba(0, 0, 0, 0));
        box-shadow: inset 2px 2px 3px rgba(255, 255, 255, 0.6), inset -2px -2px 3px rgba(0, 0, 0, 0.6);
    }

    .btn {
        text-align: center;
    }

    form {
        display: flex;
        flex-wrap: nowrap !important;
    }
    .column {
        float: left;
        width: 50%;
    }

    .row:after {
        content: "";
        display: table;
        clear: both;
    }
</style>
<body>

    <div class="Heading">
        <h3>Flight Details</h3>
    </div>
    <form action="" class="FormCls" method="post">
        <!-- Headings for the form -->
        @using (Html.BeginForm("Flights_Details", "Flights", FormMethod.Post))
        {
            <div class="container row">

                <div class="column" style="padding-left:240px;">
                    <div class="form-group">
                        @Html.LabelFor(m => m.flightId)
                        @Html.TextBoxFor(m => m.flightId, "", new { @class = "form-control", @placeholder = "FlightId" , disabled = "disabled" })
  
                        @Html.ValidationMessageFor(m => m.flightId, "", new { @class = "badge badge-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(m => m.flightName)
                        @Html.TextBoxFor(m => m.flightName, "", new { @class = "form-control", @placeholder = "flightName" })
                        @Html.ValidationMessageFor(m => m.flightName, "", new { @class = "badge badge-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.flightDate)
                        @Html.TextBoxFor(m => m.flightDate, "", new { @class = "form-control", @placeholder = "flightDate" })
                        @Html.ValidationMessageFor(m => m.flightDate, "", new { @class = "badge badge-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(m => m.fromLocation)
                        @Html.TextBoxFor(m => m.fromLocation, "", new { @class = "form-control", @placeholder = "fromLocation" })
                        @Html.ValidationMessageFor(m => m.fromLocation, "", new { @class = "badge badge-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.toLocation)
                        @Html.TextBoxFor(m => m.toLocation, "", new { @class = "form-control", @placeholder = "UserName" })
                        @Html.ValidationMessageFor(m => m.toLocation, "", new { @class = "badge badge-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.departureTime)
                        @Html.TextBoxFor(m => m.departureTime, "", new { @class = "form-control", @placeholder = "departureTime" })
                        @Html.ValidationMessageFor(m => m.departureTime, "", new { @class = "badge badge-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.timeDuration)
                        @Html.TextBoxFor(m => m.timeDuration, "", new { @class = "form-control", @placeholder = "timeDuration" })
                        @Html.ValidationMessageFor(m => m.timeDuration, "", new { @class = "badge badge-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.noOfSeats)
                        @Html.TextBoxFor(m => m.noOfSeats, "", new { @class = "form-control", @placeholder = "noOfSeats" })
                        @Html.ValidationMessageFor(m => m.noOfSeats, "", new { @class = "badge badge-danger" })
                    </div>

                </div>

                <div class="column" style="padding-left:140px;">
                    <div class="form-group">
                        @Html.LabelFor(m => m.economySeatsClass)
                        @Html.TextBoxFor(m => m.economySeatsClass, "", new { @class = "form-control", @placeholder = "economySeatsClass" })
                        @Html.ValidationMessageFor(m => m.economySeatsClass, "", new { @class = "badge badge-danger" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(m => m.economyPrice)
                        @Html.TextBoxFor(m => m.economyPrice, "", new { @class = "form-control", @placeholder = "economyPrice" })
                        @Html.ValidationMessageFor(m => m.economyPrice, "", new { @class = "badge badge-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.businessPrice)
                        @Html.TextBoxFor(m => m.businessPrice, "", new { @class = "form-control", @placeholder = "businessPrice" })
                        @Html.ValidationMessageFor(m => m.businessPrice, "", new { @class = "badge badge-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.secondClassSeats)
                        @Html.TextBoxFor(m => m.secondClassSeats, "", new { @class = "form-control", @placeholder = "secondClassSeats" })
                        @Html.ValidationMessageFor(m => m.secondClassSeats, "", new { @class = "badge badge-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.secondPrice)
                        @Html.TextBoxFor(m => m.secondPrice, "", new { @class = "form-control", @placeholder = "secondPrice" })
                        @Html.ValidationMessageFor(m => m.secondPrice, "", new { @class = "badge badge-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.firstClassSeats)
                        @Html.TextBoxFor(m => m.firstClassSeats, "", new { @class = "form-control", @placeholder = "firstClassSeats" })
                        @Html.ValidationMessageFor(m => m.firstClassSeats, "", new { @class = "badge badge-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.secondClassSeats)
                        @Html.TextBoxFor(m => m.secondClassSeats, "", new { @class = "form-control", @placeholder = "secondClassSeats" })
                        @Html.ValidationMessageFor(m => m.secondClassSeats, "", new { @class = "badge badge-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.firstPrice)
                        @Html.TextBoxFor(m => m.firstPrice, "", new { @class = "form-control", @placeholder = "firstPrice" })
                        @Html.ValidationMessageFor(m => m.firstPrice, "", new { @class = "badge badge-danger" })
                    </div>

                </div>
                <div class="container" style="padding-left:130px;">
                    <button class=" btn-success" style="padding:10px!important;">Submit</button>

                </div>
            </div>
          

        }



    </form>
   
</body>
</html>

Views/Home/About.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--<title> An About Us Page | CoderGirl </title>-->
    <!---Custom Css File!--->
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'Poppins', sans-serif;
        }

        .about-us {
            height: 100vh;
            width: 100%;
            padding: 90px 0;
            background: #fae5d3;
        }

        .pic {
            height: 300px;
            width: 302px;
        }

        .about {
            width: 1130px;
            max-width: 85%;
            margin: 0 auto;
            display: flex;
            align-items: center;
            justify-content: space-around;
        }

        .text {
            width: 540px;
        }

            .text h2 {
                font-size: 40px;
                font-weight: 600;
                margin-bottom: 10px;
            }

            .text h5 {
                font-size: 56px;
                font-weight: 500;
                margin-bottom: 20px;
            }

        span {
            color: #e67e22;
        }

        .text p {
            font-size: 16px;
            line-height: 25px;
            letter-spacing: 1px;
            font-family: "Times New Roman", Times, serif;
        }

        .data {
           // margin-top: 30px;
        }

        .hire:hover {
            background: #fae5d3;
            border: 1px solid #fae5d3;
        }
    </style>
</head>
<body>
    <section class="about-us">
        <div class="about">
            <img src="https://media.istockphoto.com/id/866616238/photo/plane-lands-at-an-airfield-at-the-sunset.jpg?b=1&s=170667a&w=0&k=20&c=b3O8p4PpZ5IGqRuBArK2Puj33vC1ZpUBaJ1FO3PsLb4=" alt="" class="pic" style="border-radius: 150%">
            <div class="text">
                <h2>About Us</h2>
                <p>
                    More than 11 million direct customers prefer using FlyFriendly for the guaranteed best price on

                    travel booking. Download FlyFriendly mobile app to search and book flight tickets We also provide attractive offers on travel through our

                    flight tickets booking app. Enjoy special discounts on first time booking and make

                    unlimited memories with FlyFriendly.
                    On the FlyFriendly flight booking app, you are guaranteed to have the best rates on flight booking. Our travel app provides a hassle-

                    free flight booking experience to the users on any handheld device. You

                    can book domestic and international flight tickets for one way and round trip.
                </p>
                <div class="data">
@*                    <a href="" class="" style="background-color: #e67e22;width: 120px;height: 30px;">Book Now </a>
*@
                    <button class=" btn-danger" style="height:40px;width:150px;">Book Now </button>
                </div>
            </div>
        </div>
        </section>
</body>
</html>

Views/Info/PrivacyPolicy.cshtml
@{
    ViewBag.Title = "PrivacyPolicy";
}

<h2>PrivacyPolicy</h2>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/Index.css")
 @*   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.1/css/bootstrap.min.css" integrity="sha512-6KY5s6UI5J7SVYuZB4S/CZMyPylqyyNZco376NM2Z8Sb8OxEdp02e1jkKk/wZxIEmjQ6DRCEBhni+gpr9c4tvA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.1/js/bootstrap.min.js" integrity="sha512-ewfXo9Gq53e1q1+WDTjaHAGZ8UvCWq0eXONhwDuIoaH8xz2r96uoAYaQCm1oQhnBfRXrvJztNXFsTloJfgbL5Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>*@

</head>
<style>

    .ftr-color{
        color:darkred;
    }
    .navbar-nav > li > a {
        // padding-top: 10px;
        //padding-bottom: 10px;
        //line-height: 20px;
        color: black;
    }
    .navbar-brand {
        font-family: serif;
        font-weight: bold;
        color: #e67e22;
        font-size: 22px;
    }

    .hvr-underline-from-center {
        display: inline-block;
        vertical-align: middle;
        -webkit-transform: translateZ(0);
        transform: translateZ(0);
        box-shadow: 0 0 1px rgba(0, 0, 0, 0);
        -webkit-backface-visibility: hidden;
        backface-visibility: hidden;
        -moz-osx-font-smoothing: blue;
        position: relative;
        overflow: hidden;
    }

        .hvr-underline-from-center:before {
            content: "";
            position: absolute;
            z-index: -1;
            left: 50%;
            right: 50%;
            bottom: 0;
            background: #cf711f;
            height: 4px;
            -webkit-transition-property: left, right;
            transition-property: left, right;
            -webkit-transition-duration: 0.3s;
            transition-duration: 0.3s;
            -webkit-transition-timing-function: ease-out;
            transition-timing-function: ease-out;
        }

        .hvr-underline-from-center:hover:before, .hvr-underline-from-center:focus:before, .hvr-underline-from-center:active:before {
            left: 0;
            right: 0;
        }


    *, *:before, *:after {
        box-sizing: border-box;
    }

    html {
        font-size: 100%;
    }

    body {
        font-family: acumin-pro, system-ui, sans-serif;
        margin: 0;
        display: grid;
        grid-template-rows: auto 1fr auto;
        font-size: 14px;
        background-color: #f4f4f4;
        align-items: start;
        min-height: 100%;
    }

    #myFyC {
        font-family: 'Pacifico', cursive;
        font-weight: 400;
        text-transform: lowercase;
        font-size: 1.5rem;
    }

    .footer {
        display: flex;
        flex-flow: row wrap;
        padding: 30px 30px 20px 50px;
        color: #2f2f2f;
        background-color: #fff;
        border-top: 1px solid #e5e5e5;
        //position:absolute;
    }

        .footer > * {
            flex: 1 100%;
        }

    .footer__addr {
        margin-right: 1.25em;
        margin-bottom: 2em;
    }

    .footer__logo {
        font-family: 'Pacifico', cursive;
        font-weight: 400;
        text-transform: lowercase;
        font-size: 1.5rem;
    }

    .footer__addr h2 {
        margin-top: 1.3em;
        font-size: 15px;
        font-weight: 400;
    }

    .nav__title {
        font-weight: 400;
        font-size: 15px;
    }

    .footer address {
        font-style: normal;
        color: #999;
    }

    .footer__btn {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 36px;
        max-width: max-content;
        background-color: rgb(33, 33, 33, 0.07);
        border-radius: 100px;
        color: #2f2f2f;
        line-height: 0;
        margin: 0.6em 0;
        font-size: 1rem;
        padding: 0 1.3em;
    }

    .footer ul {
        list-style: none;
        padding-left: 0;
    }

    .footer li {
        line-height: 2em;
    }

    .footer a {
        text-decoration: none;
    }

    .footer__nav {
        display: flex;
        flex-flow: row wrap;
    }

        .footer__nav > * {
            flex: 1 50%;
            margin-right: 1.25em;
        }

    .nav__ul a {
        // color: #999;
    }

    .nav__ul--extra {
        column-count: 2;
        column-gap: 1.25em;
    }

    .legal {
        display: flex;
        flex-wrap: wrap;
        // color: #999;
    }

    .legal__links {
        display: flex;
        align-items: center;
    }

    .heart {
        color: #2f2f2f;
    }

    @@media screen and (min-width: 24.375em) {
        .legal .legal__links {
            margin-left: auto;
        }
    }

    @@media screen and (min-width: 40.375em) {
        .footer__nav > * {
            flex: 1;
        }

        .nav__item--extra {
            flex-grow: 2;
        }

        .footer__addr {
            flex: 1 0px;
        }

        .footer__nav {
            flex: 2 0px;
        }
    }

    #myFyC {
        font-family: 'Pacifico', cursive;
        font-weight: 400;
        text-transform: lowercase;
        font-size: 1.5rem;
    }
</style>

<body>
    @* <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                </div>
            </div>
        </div>*@

    <div class="navbar  navbar-fixed-top navbar-light bg-light" style="background-color: #fdf2e9;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <span id="#myFyC"> @Html.ActionLink("FlyFriendly!", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</span>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li class="hvr-underline-from-center">@Html.ActionLink("Home", "Index", "Home")</li>

                    <li class="hvr-underline-from-center">@Html.ActionLink("Flights", "Booking", "Flights")</li>
@*                    <li class="hvr-underline-from-center">@Html.ActionLink("Contact Us", "Contact", "Home")</li>
*@                    <li class="hvr-underline-from-center">@Html.ActionLink("About Us", "About", "Home")</li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Info
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Contact us", "Contact", "Home")</li>
                            <li>@Html.ActionLink("FAQs", "FAQs", "Info")</li>
                            <li>@Html.ActionLink("Reviews", "Reviews", "Info")</li>
                            <li>@Html.ActionLink("Terms&Conditions", "Terms_Conditions", "Info")</li>

                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="hvr-underline-from-center">
                        @Html.ActionLink("Register", "Register", "Account", null, null)
                    </li>
                    <li class="hvr-underline-from-center">
                        @Html.ActionLink("Login", "Login", "Account", null, null)
                    </li>
                </ul>
            </div>
        </div>
    </div>




    <div class="">
        @RenderBody()
        <hr />
        <footer>
            <!-- Footer main -->
            <section class="ft-main">

                <div class="ft-main-item">
                    <h2 class="ft-title">About</h2>
                    <ul>
                        <li><a href="#">Services</a></li>
                        <li><a href="#">Portfolio</a></li>
                        <li><a href="#">Pricing</a></li>
                        <li><a href="#">Customers</a></li>
                        <li><a href="#">Careers</a></li>
                    </ul>
                </div>
                <div class="ft-main-item">
                    <h2 class="ft-title">Resources</h2>
                    <ul>
                        <li><a href="#">Docs</a></li>
                        <li><a href="#">Blog</a></li>
                        <li><a href="#">eBooks</a></li>
                        <li><a href="#">Webinars</a></li>
                    </ul>
                </div>
                <div class="ft-main-item">
                    <h2 class="ft-title">Contact</h2>
                    <ul>
                        <li><a href="#">Help</a></li>
                        <li><a href="#">Sales</a></li>
                        <li><a href="#">Advertise</a></li>
                    </ul>
                </div>
                <div class="ft-main-item">
                    <h2 class="ft-title">Stay Updated</h2>
                    <p  class="ftr-color">Subscribe to our newsletter to get our latest news.</p>
                    <form>
                        <input type="email" name="email" placeholder="Enter email address">
                        <input type="submit" value="Subscribe">
                    </form>
                </div>
            </section>

            <!-- Footer social -->
            <!-- Footer legal -->
            <section class="ft-legal">
                <ul class="ft-legal-list">
                    <li><a href="/Info/Terms_Conditions">Terms &amp; Conditions</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                    <li class="ftr-color">&copy; 2023 Copyright FlyFriendly Inc.</li>
                </ul>
            </section>
        </footer>

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>